### ISSUE TITLE
Ribotyper-only installation

### ISSUE THREAD

**Issue by AntonPetrov** [nawrockie/ribotyper-v1#4]
Hello! 👋

Would it be possible to provide a way to install only Ribotyper and Infernal, without Blast and other tools? 

The [R2DT project](rnacentral/R2DT) relies on ribotyper for selecting secondary structure templates, but the other software is not needed and is deleted after it is installed. Speeding up the installation process would be really useful because the R2DT Docker images would build faster, and faster builds help with CI/CD and automated testing.

Please let me know if you need any further information. Thank you!

**Comment by nawrockie** [comment]
Yes, we can do that and will include an alternative installation like you're requesting in the next release.

**Comment by nawrockie** [comment]
@AntonPetrov : this is now possible in the latest version (v1.0.5). Using the `install.sh` script without any arguments will output usage information:
```
> sh /Users/nawrockie/src/ribovore/install.sh
Usage:  /Users/nawrockie/src/ribovore/install.sh <os>
 or
Usage:   /Users/nawrockie/src/ribovore/install.sh <os> keep

valid options for <os> are:
  "linux":             full install for linux
  "macosx-intel":      full install for macosx-intel
  "macosx-silicon":    full install for macosx-silicon
  "rt-linux":          ribotyper only for linux
  "rt-macosx-intel":   ribotyper only for macosx-intel
  "rt-macosx-silicon": ribotyper only for macosx-silicon

use "keep" as 2nd argument to keep nonessential files
which are normally removed
```
