### ISSUE TITLE
Reduce the size of model databases

### ISSUE THREAD

**Issue by AntonPetrov** [nawrockie/ribotyper-v1#9]
Currently ribovore requires the models to be present on disk as individual files and also concatenated in a combined `all.cm` file. This makes the model databases difficult to manage and deploy in the context of the [R2DT](https://r2dt.bio) software that uses ribovore to search 2 large collections of models (specifically Rfam and CRW) that together take ~500 Mb with duplication. 

Could ribovore use either individual models or the concatenated file to reduce the size of the database and simplify their maintenance and deployment?

**Comment by nawrockie** [comment]
This was addressed with PR #10 and current code in the `develop` branch makes it so individual CM files are no longer necessary for `ribotyper`.

You'll need to modify the .modelinfo file by replacing the individual model file names (field 4) with `-`. 

Also, the 'master' CM library file must be indexed, this can be done with `cmfetch --index` or `cmpress`. To minimize disk space use `cmfetch --index`. If you previously included files like `all.cm.i1*` you can remove these, only `all.cm.ssi` is needed (which is created by `cmfetch --index all.cm`).
